### PR TITLE
Just organizing and styling code/imports

### PR DESCRIPTION
**Pull request by Snoop1CattZ69**
//  Little thanks for your attention to my projects.

Just organizing and styling code/imports

### CODE REVIEW

**Comment by axemwa** [comment]
ooh thank you that's much neater. It's my first plugin so i probs made the code longer than it needed to be

**Comment by Snoop1CattZ69** [comment]
Everyone goes this way at the beginning. :)

**Comment by axemwa** [comment]
its a bit to take in as I had no programming experience whatsoever prior to making that plugin, it is my 1st one

**Comment by JohOply** [comment]
Hi
Could you release this code please? :)

**Comment by axemwa** [comment]
Should already be on spigot, the plugins has a couple bugs though I have to learn how to code again to fix them as it has been a while
https://www.spigotmc.org/resources/nostrip.61574/

**Comment by JohOply** [comment]
Update date on Spigot is Dec 21, 2018

But it was merge  on github on January 2019?

**Comment by axemwa** [comment]
Oh sorry that's right cause of the bugs I haven't updated yet, I'll try fix them but might be a while as I have to learn it all again.

**Comment by JohOply** [comment]
In general I didn't see a lot of bugs, even if i'm sure there is some because you are a begginer :)
Try to ask on spigot or bukkit forums to get some help on specific question :)

Your plugin idea is really nice, I hope you will update it and fix bugs

If you need, i'm able to help you to test your dev builds ;)

**Comment by axemwa** [comment]
The known bugs are, the placeholders I added aren't working and neither is the reload command and thanks I'll let you  know how I go

**Comment by JohOply** [comment]
Seem not be huge bugs, but they are bugs. The most important bug is to fix the left hand which do not block stripping, because it is heart of the plugin :)

I have same name on Spigotmc and I already post on your thread, please send me a pm if you need :)

**Comment by axemwa** [comment]
What version is left hand not working in?

**Comment by axemwa** [comment]
minecraft version that is

**Comment by JohOply** [comment]
Latest version (1.7), like I told you on your spigot topic. I use 1.13.2-Spigot 2148b.

**Comment by axemwa** [comment]
Just post on here I get notifications on my phone and havent checked nostrip in a while

**Comment by axemwa** [comment]
See if this version works - https://www.dropbox.com/s/a982ll78iqx1zey/NoStrip-1.7.jar?dl=1
and where did u say u were using 1.13.2 I didn't get that post?

**Comment by axemwa** [comment]
also did u make sure to set permissions and toggle correctly?

**Comment by JohOply** [comment]
I created an issue right now

**Pull request merged**
